version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    restart: 'always'
    env_file:
      - docker/postgres/env.env
      - docker/env/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    networks:
      - app_network

  db:
    image: postgres:13.2-alpine
    hostname: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/postgres/env.env
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:


volumes:
  postgres_data:
